# Generated by Django 2.1.3 on 2018-11-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='title',
            field=models.TextField(default='Zawody', max_length=25),
        ),
    ]
