# Generated by Django 2.1.3 on 2018-11-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
