# Generated by Django 2.1.3 on 2018-11-20 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0003_competitor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='email',
        ),
        migrations.AlterField(
            model_name='competitor',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor', to=settings.AUTH_USER_MODEL),
        ),
    ]
