# Generated by Django 2.1.3 on 2018-11-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0004_auto_20181120_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
